/**
 * camt parser - version 1.00
 * --------------------------------------------------------
 * Report bugs and download new versions at https://github.com/psynetic-software/camt-parser
 *
 * SPDX-FileCopyrightText: 2025 psynectic
 * SPDX-License-Identifier: MIT
 * 
 */

#include "gvc_map.hpp"

namespace camt {

const char* kGvcCsvEmbedded = R"DELIM(GVC;DC;Domain;Family;SubFamily;DomDesc;FamDesc;SubDesc;Comment
006;D;PMNT;CCRD;POSC;Payments;Customer Card Transactions;Credit Card Payment;Other debit entry advice
058;C;PMNT;RCDT;FICT;Payments;Received Credit Transfers;Financial Institution Credit Transfer;Interbank payment (remittance credit)
072;C;PMNT;DRFT;STLR;Payments;Drafts;Settlement Under Reserve;Redemption of bill of exchange
073;D;PMNT;DRFT;STAM;Payments;Drafts;Settlement At Maturity;Bill of exchange
079;C;PMNT;MCOP;OTHR;Payments;Miscellaneous Credit Operations;Other;Bulk remittance
079;D;PMNT;MDOP;OTHR;Payments;Miscellaneous Debit Operations;Other;Bulk remittance
082;C;PMNT;CNTR;CDPT;Payments;Counter Transactions;Cash Deposit;Payment on an account
083;D;PMNT;CNTR;CWDL;Payments;Counter Transactions;Cash Withdrawal;Withdrawal
084;D;PMNT;RDDT;OODD;Payments;Received Direct Debits;One-Off Direct Debit;Online direct debit order
087;D;PMNT;ICDT;SDVA;Payments;Issued Credit Transfers;Same Day Value Credit Transfer;Urgent payment
088;C;PMNT;RCDT;SDVA;Payments;Received Credit Transfers;Same Day Value Credit Transfer;Remittance credit with fixed value date
093;C;PMNT;DRFT;DDFT;Payments;Drafts;Discounted Draft;Discount bill
095;C;TRAD;GUAR;OTHR;Trade Services;Guarantees;Other;Bank guarantee credit (domestic)
095;D;TRAD;GUAR;OTHR;Trade Services;Guarantees;Other;Bank guarantee credit (domestic)
098;C;PMNT;MCRD;SMCD;Payments;Merchant Card Transactions;Smart-Card Payment;Cash card (electronic wallet transactions)
101;D;PMNT;ICHQ;CCHQ;Payments;Issued Cheques;Cheque;Bearer cheque
102;D;PMNT;ICHQ;ORCQ;Payments;Issued Cheques;Order Cheque;Order cheque
103;D;PMNT;ICHQ;CCHQ;Payments;Issued Cheques;Cheque;Traveller’s cheque
104;D;PMNT;RDDT;BBDD;Payments;Received Direct Debits;SEPA B2B Direct Debit;SEPA Direct Debit (single entry – debit, B2B)
105;D;PMNT;RDDT;ESDD;Payments;Received Direct Debits;SEPA Core Direct Debit;SEPA Direct Debit (single entry – debit, Core)
106;D;PMNT;CCRD;CWDL;Payments;Customer Card Transactions;Cash Withdrawal;SEPA Card Clearing (single entry - debit)
106;D;PMNT;CCRD;SMRT;Payments;Customer Card Transactions;Smart-Card Payment;SEPA Card Clearing (single entry - debit)
106;D;PMNT;CCRD;POSD;Payments;Customer Card Transactions;Point-of-Sale (POS) Payment  - Debit Card;SEPA Card Clearing (single entry - debit)
106;D;PMNT;MCRD;CHRG;Payments;Merchant Card Transactions;Charges (Generic);SEPA Card Clearing (single entry - debit)
106;D;PMNT;CCRD;OTHR;Payments;Customer Card Transactions;Other;SEPA Card Clearing (single entry - debit)
107;D;PMNT;CCRD;OTHR;Payments;Customer Card Transactions;Other;SEPA Direct Debit (single entry - debit, direct debit generated by debit card at the point of sale)
108;D;PMNT;IDDT;UPDD;Payments;Issued Direct Debits;Reversal Due To Return/Unpaid Direct Debit;SEPA Direct Debit (debit; reversal debit,B2B)
109;D;PMNT;IDDT;UPDD;Payments;Issued Direct Debits;Reversal Due To Return/Unpaid Direct Debit;SEPA Direct Debit (debit; reversal debit, Core)
110;D;PMNT;MCRD;UPCT;Payments;Merchant Card Transactions;Unpaid Card Transaction;SEPA Card Clearing (debit; reversal debit, Core)
111;D;PMNT;ICHQ;UPCQ;Payments;Issued Cheques;Unpaid Cheque;Return account of cheques
112;D;PMNT;ICHQ;OTHR;Payments;Issued Cheques;Other;Payment order for account
112;C;PMNT;RCHQ;OTHR;Payments;Received Cheques;Other;Reverse Payment order for account
116;D;PMNT;ICDT;ESCT;Payments;Issued Credit Transfers;SEPA Credit Transfer;SEPA Credit Transfer (single entry – debit)
117;D;PMNT;ICDT;STDO;Payments;Issued Credit Transfers;Standing Order;SEPA Credit Transfer (Recurring Installment Payment – debit)
118;D;PMNT;IRCT;ESCT;Payments;Issued Real-Time Credit Transfers;SEPA Credit Transfer;SEPA Inastant Credit Transfer (single entry – debit)
119;D;PMNT;ICDT;ESCT;Payments;Issued Credit Transfers;SEPA Credit Transfer;SEPA Credit Transfer (single entry – debit, charity payment)
122;D;PMNT;ICHQ;CCHQ;Payments;Issued Cheques;Cheque;Foreign currency cheque issued in Euro
152;C;PMNT;RCDT;STDO;Payments;Received Credit Transfers;Standing Order;SEPA Credit Transfer (credit, recurring installment payment)
153;C;PMNT;RCDT;SALA;Payments;Received Credit Transfers;Payroll/Salary Payment;SEPA Credit Transfer (single entry – credit, wages, salaries, pension credit)
154;C;PMNT;RCDT;ESCT;Payments;Received Credit Transfers;SEPA Credit Transfer;SEPA Credit Transfer (single entry – credit, capital building fringe fortune)
155;C;PMNT;RCDT;ESCT;Payments;Received Credit Transfers;SEPA Credit Transfer;SEPA Credit Transfer (single entry – credit, capital building fringe fortune for retirement)
156;C;PMNT;RCDT;ESCT;Payments;Received Credit Transfers;SEPA Credit Transfer;SEPA Credit Transfer (single entry – credit, remittances of public treasuries)
157;C;PMNT;RRCT;SALA;Payments;Received Real-Time Credit Transfers;Payroll/Salary Payment;SEPA Instant Credit Transfer
159;C;PMNT;ICDT;RRTN;Payments;Issued Credit Transfers;Reversal Due To Payment Return;SEPA Credit Transfer back posting (single entry – credit, wages, salaries, pension credit)
159;D;PMNT;RCDT;RRTN;Payments;Received Credit Transfers;Reversal Due To Payment Return;(single entry – credit, wages, salaries, pension credit)
160;C;PMNT;IRCT;RRTN;Payments;Issued Real-Time Credit Transfers;Reversal Due To Payment Return;SEPA Instant Credit Transfer back posting (resulting from remittance that cannot be credited or recall)
160;D;PMNT;RRCT;RRTN;Payments;Received Real-Time Credit Transfers;Reversal Due To Payment Return;SEPA Instant Credit Transfer back posting (resulting from remittance that cannot be credited or recall)
161;C;PMNT;RRCT;ESCT;Payments;Received Real-Time Credit Transfers;SEPA Credit Transfer;SEPA Instant Credit Transfer
162;C;PMNT;RRCT;ESCT;Payments;Received Real-Time Credit Transfers;SEPA Credit Transfer;(Einzelbuchung-Haben, capital building fringe fortune)
163;C;PMNT;RRCT;ESCT;Payments;Received Real-Time Credit Transfers;SEPA Credit Transfer;SEPA Instant Credit Transfer
164;C;PMNT;RRCT;ESCT;Payments;Received Real-Time Credit Transfers;SEPA Credit Transfer;(single entry – credit, capital building fringe fortune for retirement)
165;C;PMNT;RRCT;ESCT;Payments;Received Real-Time Credit Transfers;SEPA Credit Transfer;SEPA Instant Credit Transfer (single entry – credit, Spende)
166;C;PMNT;RCDT;ESCT;Payments;Received Credit Transfers;SEPA Credit Transfer;SEPA Credit Transfer (single entry – credit)
167;C;PMNT;RCDT;ESCT;Payments;Received Credit Transfers;SEPA Credit Transfer;SEPA Credit Transfer (single entry – credit, credit transfer with checksum-protected reference data (RF))
168;C;PMNT;RRCT;ESCT;Payments;Received Real-Time Credit Transfers;SEPA Credit Transfer;SEPA Instant Credit Transfer (single entry – credit)
169;C;PMNT;RCDT;ESCT;Payments;Received Credit Transfers;SEPA Credit Transfer;SEPA Credit Transfer (single entry – credit, charity payment)
170;C;PMNT;RCHQ;URCQ;Payments;Received Cheques;Cheque Under Reserve;Credit entry related to a cheque presentation
171;C;PMNT;IDDT;ESDD;Payments;Issued Direct Debits;SEPA Core Direct Debit;SEPA Direct Debit submission (single entry – credit, Core)
174;C;PMNT;IDDT;BBDD;Payments;Issued Direct Debits;SEPA B2B Direct Debit;SEPA Direct Debit (single entry – credit, B2B)
177;D;PMNT;ICDT;ESCT;Payments;Issued Credit Transfers;SEPA Credit Transfer;SEPA Credit Transfer Online (single entry - debit)
181;C;PMNT;RDDT;UPDD;Payments;Received Direct Debits;Reversal Due To Return/Unpaid Direct Debit;SEPA Direct Debit (credit; recredit, Core)
182;C;PMNT;CCRD;RIMB;Payments;Customer Card Transactions;Reimbursement (Generic);SEPA Card Clearing (credit; recredit)
183;C;PMNT;RCHQ;UPCQ;Payments;Received Cheques;Unpaid Cheque;Return of cheque
184;C;PMNT;RDDT;UPDD;Payments;Received Direct Debits;Reversal Due To Return/Unpaid Direct Debit;SEPA Direct Debit (credit; recredit, B2B)
185;D;PMNT;ICHQ;CCHQ;Payments;Issued Cheques;Cheque;Cheque debit (bulk posting debit)
188;D;PMNT;IRCT;ESCT;Payments;Issued Real-Time Credit Transfers;SEPA Credit Transfer;reserved for: SEPA Credit Transfer Instant (bulk-posting debit)
189;C;PMNT;RRCT;ESCT;Payments;Received Real-Time Credit Transfers;SEPA Credit Transfer;SEPA Instant Credit Transfer (bulk posting credit)
190;D;PMNT;CCRD;OTHR;Payments;Customer Card Transactions;Other;SEPA Card Clearing (bulk posting debit)
191;D;PMNT;ICDT;ESCT;Payments;Issued Credit Transfers;SEPA Credit Transfer;SEPA Credit Transfer (bulk posting debit)
192;C;PMNT;IDDT;ESDD;Payments;Issued Direct Debits;SEPA Core Direct Debit;SEPA Direct Debit (bulk posting credit, Core)
193;D;PMNT;IDDT;RCDD;Payments;Issued Direct Debits;Reversal Due To Payment Cancellation Request;SEPA Direct Debit (debit, reversal)
194;C;PMNT;RCDT;ESCT;Payments;Received Credit Transfers;SEPA Credit Transfer;SEPA Credit Transfer (bulk posting credit)
195;D;PMNT;RDDT;ESDD;Payments;Received Direct Debits;SEPA Core Direct Debit;SEPA Direct Debit (bulk posting debit, Core)
196;C;PMNT;IDDT;BBDD;Payments;Issued Direct Debits;SEPA B2B Direct Debit;SEPA Direct Debit (bulk posting credit, B2B)
197;D;PMNT;RDDT;BBDD;Payments;Received Direct Debits;SEPA B2B Direct Debit;SEPA Direct Debit (bulk posting debit, B2B)
198;C;PMNT;MCRD;POSP;Payments;Merchant Card Transactions;Point-of-Sale (POS) Payment;SEPA Card Clearing (bulk posting credit)
199;D;PMNT;MCRD;DAJT;Payments;Merchant Card Transactions;Debit Adjustments (Generic);SEPA Card Clearing (debit, reversal)
)DELIM"
R"DELIM(
201;D;PMNT;ICDT;XBCT;Payments;Issued Credit Transfers;Cross-Border Credit Transfer;Payment order
202;C;PMNT;RCDT;XBCT;Payments;Received Credit Transfers;Cross-Border Credit Transfer;Cross-border payment (credit)
201;D;PMNT;ICDT;XBSA;Payments;Issued Credit Transfers;Cross-Border Payroll/Salary Payment;Payment order salary
202;C;PMNT;RCDT;XBSA;Payments;Received Credit Transfers;Cross-Border Payroll/Salary Payment;Cross-border payment salary
201;D;PMNT;RCDT;XRTN;Payments;Received Credit Transfers;Cross Border Reversal Due to Payment Return;Return receipt of payment
202;C;PMNT;ICDT;XRTN;Payments;Issued Credit Transfers;Cross Border Reversal Due to Payment Return;Re-credit AZV payment
203;C;TRAD;CLNC;OTHR;Trade Services;Clean Collection;Other;Collection
203;D;TRAD;CLNC;OTHR;Trade Services;Clean Collection;Other;Collection
204;C;TRAD;DCCT;OTHR;Trade Services;Documentary Credit;Other;Letter of credit
204;D;TRAD;DCCT;OTHR;Trade Services;Documentary Credit;Other;Letter of credit
205;C;TRAD;GUAR;OTHR;Trade Services;Guarantees;Other;Bank guarantee credit 
205;D;TRAD;GUAR;OTHR;Trade Services;Guarantees;Other;Bank guarantee credit 
206;C;PMNT;RCDT;XBCT;Payments;Received Credit Transfers;Cross-Border Credit Transfer;Cross-border remittance 
208;C;TRAD;MCOP;RIMB;Trade Services;Miscellaneous Credit Operations;Reimbursement (Generic);Reimbursement
208;D;TRAD;MDOP;RIMB;Trade Services;Miscellaneous Debit Operations;Reimbursement (Generic);Reimbursement
209;D;PMNT;ICHQ;CCCH;Payments;Issued Cheques;Certified Customer Cheque;Cheque payment
210;D;PMNT;ICDT;XBCT;Payments;Issued Credit Transfers;Cross-Border Credit Transfer;Electronic payment
212;D;PMNT;ICDT;XBST;Payments;Issued Credit Transfers;Cross-Border Standing Order;Standing order
213;D;PMNT;RDDT;XBDD;Payments;Received Direct Debits;Cross-Border Direct Debit;Cross-border direct debit
214;D;TRAD;DOCC;OTHR;Trade Services;Documentary Collection;Other;Documentary collection (Import)
215;C;TRAD;DOCC;OTHR;Trade Services;Documentary Collection;Other;Documentary collection (Export)
216;D;PMNT;DRFT;STAM;Payments;Drafts;Settlement At Maturity;Bill of exchange collection (Import)
217;C;PMNT;DRFT;STAM;Payments;Drafts;Settlement At Maturity;Bill of exchange collection (Export)
217;C;PMNT;DRFT;STLR;Payments;Drafts;Settlement Under Reserve;Bill of exchange collection (Export)
218;D;TRAD;DCCT;SOSI;Trade Services;Documentary Credit;Settlement Of Sight Import Document;Import letter of credit
219;C;TRAD;DCCT;SOSE;Trade Services;Documentary Credit;Settlement Of Sight Export Document;Export letter of credit
220;C;PMNT;RCHQ;XRCQ;Payments;Received Cheques;Foreign Cheque Under Reserve;Foreign cheque credit (subject to collection) 
221;C;PMNT;RCHQ;XBCQ;Payments;Received Cheques;Foreign Cheque;Credit for foreign cheque collection 
222;D;PMNT;ICHQ;XBCQ;Payments;Issued Cheques;Foreign Cheque;Cross border cheque debit
224;C;PMNT;CNTR;FCDP;Payments;Counter Transactions;Foreign Currencies Deposit;Purchase of foreign currencies
225;D;PMNT;CNTR;FCWD;Payments;Counter Transactions;Foreign Currencies Withdrawal;Sale of foreign currencies
301;C;SECU;CUST;OTHR;Securities;Custody;Other;Collection
302;C;SECU;CUST;DVCA;Securities;Custody;Cash Dividend;Coupons/Dividends
303;C;SECU;SETT;TRAD;Securities;Trade, Clearing and Settlement;Trade;Stocks and bonds
303;D;SECU;SETT;TRAD;Securities;Trade, Clearing and Settlement;Trade;Stocks and bonds
304;C;SECU;MCOP;ADJT;Securities;Miscellaneous Credit Operations;Adjustments (Generic);Carry-over
304;D;SECU;MDOP;ADJT;Securities;Miscellaneous Debit Operations;Adjustments (Generic);Carry-over
305;D;SECU;CUST;OTHR;Securities;Custody;Other;Registered bond
306;D;SECU;OTHR;OTHR;Securities;Other;Other;Promissory note
307;D;SECU;SETT;SUBS;Securities;Trade, Clearing and Settlement;Subscription;Subscription of securities
308;C;SECU;CORP;EXWA;Securities;Corporate Action;Warrant Exercise/Warrant Conversion;Subscription rights trade
308;D;SECU;CORP;EXWA;Securities;Corporate Action;Warrant Exercise/Warrant Conversion;Subscription rights trade
309;C;SECU;CORP;BONU;Securities;Corporate Action;Bonus Issue/Capitalisation Issue;Subscription rights trade
309;D;SECU;CORP;BONU;Securities;Corporate Action;Bonus Issue/Capitalisation Issue;Bonus rights trade
310;C;SECU;MCOP;OTHR;Securities;Miscellaneous Credit Operations;Other;Option trading
310;D;SECU;MDOP;OTHR;Securities;Miscellaneous Debit Operations;Other;Option trading
311;C;DERV;OTHR;OTHR;Derivatives;Other;Other;Futures transactions
311;D;DERV;OTHR;OTHR;Derivatives;Other;Other;Futures transactions
320;D;SECU;CASH;TRFE;Securities;Miscellaneous Securities Operations;Transaction Fees;Securities transaction fees
321;D;SECU;CUST;CHRG;Securities;Custody;Charges (Generic);Custodian fees
321;C;SECU;CUST;CHRG;Securities;Custody;Charges (Generic);Custodian fees
330;C;SECU;CUST;INTR;Securities;Custody;Interests (Generic);Securities income
340;C;SECU;CUST;REDM;Securities;Custody;Final Maturity;Credit for matured securities
399;C;ACMT;ACOP;PSTE;Account Management;Additional  Miscellaneous Credit Operations;Posting Error;Reversal
399;D;ACMT;ADOP;PSTE;Account Management;Additional Miscellaneous Debit Operations;Posting Error;Reversal
)DELIM"
R"DELIM(
403;D;FORX;MDOP;OTHR;Foreign Exchange;Miscellaneous Debit Operations;Other;Foreign exchange for travel purposes
404;D;FORX;OTHR;OTHR;Foreign Exchange;Other;Other;Foreign currency cheque
405;D;FORX;OTHR;OTHR;Foreign Exchange;Other;Other;Financial innovations
406;C;FORX;SPOT;OTHR;Foreign Exchange;Spots;Other;FX-Deal
406;D;FORX;SPOT;OTHR;Foreign Exchange;Spots;Other;FX-Deal
407;C;FORX;OTHR;OTHR;Foreign Exchange;Other;Other;Money marked deal
407;D;FORX;OTHR;OTHR;Foreign Exchange;Other;Other;Money marked deal
408;C;FORX;MCOP;INTR;Foreign Exchange;Miscellaneous Credit Operations;Interests (Generic);Interest money marked
409;C;FORX;MCOP;OTHR;Foreign Exchange;Miscellaneous Credit Operations;Other;Interest plus principal
411;D;FORX;SPOT;OTHR;Foreign Exchange;Spots;Other;Spot exchange: purchase
412;C;FORX;SPOT;OTHR;Foreign Exchange;Spots;Other;Spot exchange: sale
413;D;FORX;FWRD;OTHR;Foreign Exchange;Forwards;Other;Forward exchange: purchase
414;C;FORX;FWRD;OTHR;Foreign Exchange;Forwards;Other;Forward exchange: sale
415;D;FORX;MDOP;OTHR;Foreign Exchange;Miscellaneous Debit Operations;Other;In Foreign currency Overnight money: active
416;C;FORX;MCOP;OTHR;Foreign Exchange;Miscellaneous Credit Operations;Other;In Foreign currency Overnight money: passive
417;D;FORX;MDOP;OTHR;Foreign Exchange;Miscellaneous Debit Operations;Other;In Foreign currency Fixed-term deposit: active
418;C;FORX;MCOP;OTHR;Foreign Exchange;Miscellaneous Credit Operations;Other;In Foreign currency Fixed-term deposit: passive
419;D;FORX;MDOP;OTHR;Foreign Exchange;Miscellaneous Debit Operations;Other;Call money: active
420;C;FORX;MCOP;OTHR;Foreign Exchange;Miscellaneous Credit Operations;Other;Call money: passive
421;C;FORX;MCOP;OTHR;Foreign Exchange;Miscellaneous Credit Operations;Other;Options
421;D;FORX;MDOP;OTHR;Foreign Exchange;Miscellaneous Debit Operations;Other;Options
422;C;FORX;SWAP;OTHR;Foreign Exchange;Swaps;Other;Swap
422;D;FORX;SWAP;OTHR;Foreign Exchange;Swaps;Other;Swap
423;C;PMET;SPOT;OTHR;Precious Metal;Spots;Other;Precious metal: purchase
424;D;PMET;SPOT;OTHR;Precious Metal;Spots;Other;Precious metal: sale
601;D;LDAS;FTLN;OTHR;Loans, Deposits & Syndications;Fixed Term Loans;Other;Collection of instalments/annuities
602;C;LDAS;FTLN;OTHR;Loans, Deposits & Syndications;Fixed Term Loans;Other;Remittance of instalments/annuities
603;D;LDAS;FTLN;PPAY;Loans, Deposits & Syndications;Fixed Term Loans;Principal Payment;Redemption
604;D;LDAS;MDOP;INTR;Loans, Deposits & Syndications;Miscellaneous Debit Operations;Interests (Generic);Interest on loan
605;D;LDAS;MDOP;INTR;Loans, Deposits & Syndications;Miscellaneous Debit Operations;Interests (Generic);Interest on loan with additional services
606;C;LDAS;FTLN;DDWN;Loans, Deposits & Syndications;Fixed Term Loans;Drawdown;Loan principal amount
606;D;LDAS;FTLN;DDWN;Loans, Deposits & Syndications;Fixed Term Loans;Drawdown;Loan principal amount
607;D;LDAS;OTHR;OTHR;Loans, Deposits & Syndications;Other;Other;Repayment principal amount and/or interest
)DELIM"
R"DELIM(
801;D;ACMT;MDOP;CHRG;Account Management;Miscellaneous Debit Operations;Charges (Generic);Cheque card
802;D;ACMT;MDOP;CHRG;Account Management;Miscellaneous Debit Operations;Charges (Generic);Cheque book
805;C;ACMT;OPCL;ACCC;Account Management;Opening & Closing;Account Closing;Standing order charge
805;D;ACMT;OPCL;ACCC;Account Management;Opening & Closing;Account Closing;Standing order charge
806;C;ACMT;MCOP;CHRG;Account Management;Miscellaneous Credit Operations;Charges (Generic);Postage and handling (or respective refund)
806;D;ACMT;MDOP;CHRG;Account Management;Miscellaneous Debit Operations;Charges (Generic);Postage and handling (or respective refund)
807;C;ACMT;MCOP;CHRG;Account Management;Miscellaneous Credit Operations;Charges (Generic);Fees and expenses (or respective refund)
807;D;ACMT;MDOP;CHRG;Account Management;Miscellaneous Debit Operations;Charges (Generic);Fees and expenses (or respective refund)
808;C;ACMT;MCOP;CHRG;Account Management;Miscellaneous Credit Operations;Charges (Generic);Refund of Charges
808;D;ACMT;MDOP;CHRG;Account Management;Miscellaneous Debit Operations;Charges (Generic);Charges
808;C;PMNT;MCOP;CHRG;Payments;Miscellaneous Credit Operations;Charges (Generic);Refund of Charges
808;D;PMNT;MDOP;CHRG;Payments;Miscellaneous Debit Operations;Charges (Generic);Charges
808;C;TRAD;MCOP;CHRG;Trade Services;Miscellaneous Credit Operations;Charges (Generic);Refund of Charges
808;D;TRAD;MDOP;CHRG;Trade Services;Miscellaneous Debit Operations;Charges (Generic);Charges
809;D;ACMT;MDOP;COMM;Account Management;Miscellaneous Debit Operations;Commission (Generic);Brokerage
809;C;ACMT;MCOP;COMM;Account Management;Miscellaneous Credit Operations;Commission (Generic);Refund of Brokerage
809;D;PMNT;MDOP;COMM;Payments;Miscellaneous Debit Operations;Commission (Generic);Brokerage
809;C;PMNT;MCOP;COMM;Payments;Miscellaneous Credit Operations;Commission (Generic);Refund of Brokerage
809;D;TRAD;MDOP;COMM;Trade Services;Miscellaneous Debit Operations;Commission (Generic);Brokerage
809;C;TRAD;MCOP;COMM;Trade Services;Miscellaneous Credit Operations;Commission (Generic);Refund of Brokerage
809;D;LDAS;MDOP;COMM;Loans, Deposits & Syndications;Miscellaneous Debit Operations;Commission (Generic);Brokerage
809;C;LDAS;MCOP;COMM;Loans, Deposits & Syndications;Miscellaneous Credit Operations;Commission (Generic);Refund of Brokerage
810;D;ACMT;MDOP;CHRG;Account Management;Miscellaneous Debit Operations;Charges (Generic);Reminder charges
810;C;ACMT;MCOP;CHRG;Account Management;Miscellaneous Credit Operations;Charges (Generic);Refund of Reminder charges
811;D;LDAS;MDOP;CHRG;Loans, Deposits & Syndications;Miscellaneous Debit Operations;Charges (Generic);Credit costs
811;C;LDAS;MCOP;CHRG;Loans, Deposits & Syndications;Miscellaneous Credit Operations;Charges (Generic);Refund of Credit costs
812;D;LDAS;MDOP;INTR;Loans, Deposits & Syndications;Miscellaneous Debit Operations;Interests (Generic);Interest charged for deferred payment
812;C;LDAS;MCOP;INTR;Loans, Deposits & Syndications;Miscellaneous Credit Operations;Interests (Generic);Refund of Interest charged for deferred payment
813;D;LDAS;MDOP;INTR;Loans, Deposits & Syndications;Miscellaneous Debit Operations;Interests (Generic);Discount
814;C;ACMT;MCOP;INTR;Account Management;Miscellaneous Credit Operations;Interests (Generic);Interest
814;D;ACMT;MDOP;INTR;Account Management;Miscellaneous Debit Operations;Interests (Generic);Interest
815;C;ACMT;OTHR;OTHR;Account Management;Other;Other;Capitalised interest
816;C;ACMT;OTHR;OTHR;Account Management;Other;Other;Change of interest rate
817;C;ACMT;OTHR;OTHR;Account Management;Other;Other;Correction of interest
817;D;ACMT;OTHR;OTHR;Account Management;Other;Other;Correction of interest
819;C;PMNT;MCOP;OTHR;Payments;Miscellaneous Credit Operations;Other;Remuneration
820;C;PMNT;RCDT;BOOK;Payments;Received Credit Transfers;Internal Book Transfer;Carry-over
820;D;PMNT;ICDT;BOOK;Payments;Issued Credit Transfers;Internal Book Transfer;Carry-over
821;D;PMNT;MDOP;OTHR;Payments;Miscellaneous Debit Operations;Other;Telephone
822;C;PMNT;MCOP;OTHR;Payments;Miscellaneous Credit Operations;Other;Payment plan
823;C;LDAS;FTDP;RPMT;Loans, Deposits & Syndications;Fixed Term Deposits;Repayment;Fixed-term deposits
823;D;LDAS;FTDP;DPST;Loans, Deposits & Syndications;Fixed Term Deposits;Deposit;Fixed-term deposits
824;D;LDAS;OTHR;OTHR;Loans, Deposits & Syndications;Other;Other;Moeny fpr lending or donating purposes
825;D;LDAS;OTHR;OTHR;Loans, Deposits & Syndications;Other;Other;Universal loan
826;D;LDAS;OTHR;OTHR;Loans, Deposits & Syndications;Other;Other;ddynamic savings
827;D;LDAS;OTHR;OTHR;Loans, Deposits & Syndications;Other;Other;Surplus savings
828;C;LDAS;FTDP;RPMT;Loans, Deposits & Syndications;Fixed Term Deposits;Repayment;Savings certificate
828;D;LDAS;FTDP;DPST;Loans, Deposits & Syndications;Fixed Term Deposits;Deposit;Savings certificate
829;C;LDAS;FTDP;RPMT;Loans, Deposits & Syndications;Fixed Term Deposits;Repayment;Savings plan
829;D;LDAS;FTDP;DPST;Loans, Deposits & Syndications;Fixed Term Deposits;Deposit;Savings plan
830;C;LDAS;FTDP;INTR;Loans, Deposits & Syndications;Fixed Term Deposits;Interests (Generic);Bonus
831;D;XTND;NTAV;NTAV;Extended Domain;Not Available;Not Available;Old invoice
832;D;LDAS;OTHR;OTHR;Loans, Deposits & Syndications;Other;Other;Mortgage
833;C;CAMT;CAPL;OTHR;Cash Management;Cash Pooling;Other;Cash concentration: main account
833;D;CAMT;CAPL;OTHR;Cash Management;Cash Pooling;Other;Cash concentration: main account
834;C;CAMT;CAPL;OTHR;Cash Management;Cash Pooling;Other;Cash concentration: subsidiary account
834;D;CAMT;CAPL;OTHR;Cash Management;Cash Pooling;Other;Cash concentration: subsidiary account
835;C;XTND;NTAV;NTAV;Extended Domain;Not Available;Not Available;Other non-defined transaction types
835;D;XTND;NTAV;NTAV;Extended Domain;Not Available;Not Available;Other non-defined transaction types
836;C;ACMT;MCOP;ADJT;Account Management;Miscellaneous Credit Operations;Adjustments (Generic);Complaint posting
836;D;ACMT;MDOP;ADJT;Account Management;Miscellaneous Debit Operations;Adjustments (Generic);Complaint posting
837;D;ACMT;MDOP;TAXE;Account Management;Miscellaneous Debit Operations;Taxes (Generic);Value added tax / sales tax
888;C;XTND;NTAV;NTAV;Extended Domain;Not Available;Not Available;Payment transfer due to Euro conversion
888;D;XTND;NTAV;NTAV;Extended Domain;Not Available;Not Available;Payment transfer due to Euro conversion
899;C;ACMT;ACOP;PSTE;Account Management;Additional  Miscellaneous Credit Operations;Posting Error;Reversal
899;D;ACMT;ADOP;PSTE;Account Management;Additional Miscellaneous Debit Operations;Posting Error;Reversal
997;D;XTND;NTAV;NTAV;Extended Domain;Not Available;Not Available;List of safekeeping accounts     -> MT 571
999;C;XTND;NTAV;NTAV;Extended Domain;Not Available;Not Available;Unstructured assignment of remittance information field '86'
999;D;XTND;NTAV;NTAV;Extended Domain;Not Available;Not Available;Unstructured assignment of remittance information field '86')DELIM";

} // namespace camt